################################################################################
# Meshtastic BLE → MQTT Gateway
# ESPHome configuration
#
# Target: ESP32-C3 (recommended), ESP32-S3, or classic ESP32
# NOTE: ESP32-S2 is not supported — it has no BLE hardware.
#
# Copy secrets.yaml.example → secrets.yaml and fill in your values before
# flashing.
################################################################################

esphome:
  name: meshtastic-gateway
  friendly_name: Meshtastic Gateway

esp32:
  # Swap board to match your hardware, e.g.:
  #   esp32dev            — classic 38-pin dev board
  #   esp32-c3-devkitm-1  — ESP32-C3 (recommended, low power)
  #   esp32-s3-devkitc-1  — ESP32-S3
  board: esp32-c3-devkitm-1
  framework:
    # esp-idf is required for full BLE client (NimBLE) support.
    # arduino framework does not expose the GATTC APIs needed.
    type: esp-idf
    version: recommended

external_components:
  - source:
      type: local
      path: components

# ── Logging ──────────────────────────────────────────────────────────────────
logger:
  level: DEBUG
  # Set to INFO once stable to reduce MQTT noise

# ── OTA & API ────────────────────────────────────────────────────────────────
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

# ── WiFi ─────────────────────────────────────────────────────────────────────
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Fallback AP if WiFi is unreachable
  ap:
    ssid: "MeshtasticGW Fallback"
    password: !secret ap_password

captive_portal:

# ── MQTT ─────────────────────────────────────────────────────────────────────
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port          # typically 1883 (or 8883 for TLS)
  username: !secret mqtt_username
  password: !secret mqtt_password
  # Gateway availability — Home Assistant uses this to mark entities unavailable
  birth_message:
    topic: meshtastic/gateway/status
    payload: online
    retain: true
  will_message:
    topic: meshtastic/gateway/status
    payload: offline
    retain: true
  # Uncomment for TLS:
  # certificate_authority: !secret mqtt_ca_cert

# ── Meshtastic BLE Component ──────────────────────────────────────────────────
meshtastic_ble:
  # BLE advertised name of your Meshtastic node (check the Meshtastic app).
  # Alternatively set node_mac to a MAC address (see component docs).
  node_name: !secret meshtastic_node_name

  # Root MQTT topic prefix.  Packets are published under:
  #   <topic_prefix>/<node_id>/...
  topic_prefix: meshtastic

  # How long to wait (seconds) before retrying a failed BLE connection.
  reconnect_interval: 30

  # Optionally hard-code the node MAC instead of scanning by name:
  # node_mac: "AA:BB:CC:DD:EE:FF"
