################################################################################
# Meshtastic BLE → MQTT Gateway
# ESPHome configuration
#
# Target: ESP32-C3 (recommended), ESP32-S3, or classic ESP32
# NOTE: ESP32-S2 is not supported — it has no BLE hardware.
#
# Copy secrets.yaml.example → secrets.yaml and fill in your values before
# flashing.
################################################################################

esphome:
  name: meshtastic-gateway
  friendly_name: Meshtastic Gateway

esp32:
  # Swap board to match your hardware, e.g.:
  #   esp32dev            — classic 38-pin dev board
  #   esp32-c3-devkitm-1  — ESP32-C3 (recommended, low power)
  #   esp32-s3-devkitc-1  — ESP32-S3
  board: esp32-c3-devkitm-1
  framework:
    # esp-idf is required for full BLE client (NimBLE) support.
    # arduino framework does not expose the GATTC APIs needed.
    type: esp-idf
    version: recommended

    # ── NimBLE Kconfig ──────────────────────────────────────────────────────
    sdkconfig_options:
      # Enable Bluetooth and select NimBLE (not Bluedroid).
      # NimBLE is the only BLE host that exposes the low-level GATTC APIs
      # (ble_gattc_disc_svc_by_uuid, ble_gattc_read, etc.) we rely on.
      CONFIG_BT_ENABLED: "y"
      CONFIG_BT_NIMBLE_ENABLED: "y"

      # Central role only — peripheral saves ~20 KB RAM.
      CONFIG_BT_NIMBLE_ROLE_CENTRAL: "y"
      CONFIG_BT_NIMBLE_ROLE_PERIPHERAL: "n"
      CONFIG_BT_NIMBLE_ROLE_BROADCASTER: "n"
      CONFIG_BT_NIMBLE_ROLE_OBSERVER: "n"

      # Negotiate 512-byte ATT MTU so full fromRadio packets fit in one read.
      CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU: "512"

      # We only ever connect to one Meshtastic node at a time.
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "1"

      # Device name seen by BLE scanners (informational only for a central).
      CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME: "meshtastic-gw"

      # Host task stack: NimBLE event loop runs in its own FreeRTOS task.
      # 5120 bytes is comfortable for the GATT callback chain; increase to
      # 8192 if you see "***ERROR*** A stack overflow in task nimble_host".
      CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE: "5120"

    # ── ESPHome loop task ────────────────────────────────────────────────────
    # The ESPHome loop task handles our state machine and the fromRadio drain.
    # 16 KB avoids overflow when nanopb decodes large NodeInfo batches.
    loop_task_stack_size: 16384

external_components:
  - source:
      type: local
      path: components

# ── Logging ──────────────────────────────────────────────────────────────────
logger:
  level: DEBUG
  # Set to INFO once stable to reduce MQTT noise

# ── OTA & API ────────────────────────────────────────────────────────────────
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

# ── WiFi ─────────────────────────────────────────────────────────────────────
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Fallback AP if WiFi is unreachable
  ap:
    ssid: "MeshtasticGW Fallback"
    password: !secret ap_password

captive_portal:

# ── MQTT ─────────────────────────────────────────────────────────────────────
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port          # typically 1883 (or 8883 for TLS)
  username: !secret mqtt_username
  password: !secret mqtt_password
  # Gateway availability — Home Assistant uses this to mark entities unavailable
  birth_message:
    topic: meshtastic/gateway/status
    payload: online
    retain: true
  will_message:
    topic: meshtastic/gateway/status
    payload: offline
    retain: true
  # Uncomment for TLS:
  # certificate_authority: !secret mqtt_ca_cert

# ── Meshtastic BLE Component ──────────────────────────────────────────────────
meshtastic_ble:
  # BLE advertised name of your Meshtastic node (check the Meshtastic app).
  # Alternatively set node_mac to a MAC address (see component docs).
  node_name: !secret meshtastic_node_name

  # Root MQTT topic prefix.  Packets are published under:
  #   <topic_prefix>/<node_id>/...
  topic_prefix: meshtastic

  # How long to wait (seconds) before retrying a failed BLE connection.
  reconnect_interval: 30

  # Optionally hard-code the node MAC instead of scanning by name:
  # node_mac: "AA:BB:CC:DD:EE:FF"
